import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>calculator app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main  className="h-screen bg-bgTheme1-mainBg flex items-center justify-center ">
        <h1 className="text-2xl text-white font-bold myFont">CALCULATOR APP SOON...</h1>
      </main> 
    </>
  )
}
